version: "3.7"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: elastic
    environment:
      - node.name=elastic
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - backend

  webpack-server:
    image: node:14-stretch
    command: /bin/bash -c '/usr/local/bin/yarn install && /usr/local/bin/yarn run webpack --mode development --watch'
    networks:
      - backend
    volumes:
      - ./natlas-server:/app
      - html_assets:/app/static/dist
    working_dir: /app

  natlas-server:
    build: natlas-server
    command: flask run --host 0.0.0.0
    ports:
      - 5000:5000
    networks:
      - backend
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - FLASK_ENV=development
      - SERVER_NAME=localhost:5000
      - PREFERRED_URL_SCHEME=http
      - SECRET_KEY=jasonkeepsbreakingmyshit
    volumes:
      - ns-data:/data
      - ./natlas-server:/opt/natlas/natlas-server
      - html_assets:/opt/natlas/natlas-server/static/dist
    links:
      - elastic

  natlas-agent:
    build: natlas-agent
    networks:
      - backend
    environment:
      - NATLAS_SERVER_ADDRESS=http://natlas-server:5000
      - NATLAS_SCAN_LOCAL=true
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp=./natlas-agent/chrome.json
    volumes:
      - ./natlas-agent:/opt/natlas/natlas-agent
    links:
      - natlas-server

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
      SERVER_HOST: 0.0.0.0
    ports:
      - 5601
    networks:
      - backend

networks:
  backend:

volumes:
  ns-data:
  elastic:
  node_modules:
  html_assets:
